#!/usr/bin/env bash
set -eou pipefail
source "$($(dirname $0)/adr-config)"

for f in $(cd "$ADR_BIN_DIR" && find . -name 'adr-*')
do
	if [ -x "$ADR_BIN_DIR/$f" ]
	then
		echo "$f" | cut -c 7-
	fi
done
