#!/usr/bin/env bash
# Config for when running from the source directory.

basedir=$(cd -L "$(dirname "$0")" >/dev/null 2>&1 && pwd -L)

export adr_bin_dir="${basedir}"
export adr_template_dir="${basedir}"
