#!/usr/bin/env bash
set -eou pipefail
source "$($(dirname $0)/adr-config)"

## usage: adr list
##
## Lists the architecture decision records

adr_dir=$("$ADR_BIN_DIR/_adr_dir")

if [ -d $adr_dir ]
then
   find $adr_dir | grep -E "^$adr_dir/[0-9]+-[^/]*\\.md" | sort
else
    echo "The $adr_dir directory does not exist"
    exit 1
fi

