#!/usr/bin/env bash
# Config for when running from the source directory.

basedir=$(cd -L "$(dirname "$0")" >/dev/null 2>&1 && pwd -L)

export ADR_BIN_DIR="${basedir}"
export ADR_TEMPLATE_DIR="${basedir}"
